// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEEGWS8V5DjOydfx8udk-6HK16LoO3mkg',
    appId: '1:358203995156:android:cbd83917480e523416e301',
    messagingSenderId: '358203995156',
    projectId: 'instagram-clone-d78a1',
    databaseURL: 'https://instagram-clone-d78a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'instagram-clone-d78a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRSK71ctxq_NQbnoACwNPMzqLOQaRXV0I',
    appId: '1:358203995156:ios:bdc173487a9563bc16e301',
    messagingSenderId: '358203995156',
    projectId: 'instagram-clone-d78a1',
    databaseURL: 'https://instagram-clone-d78a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'instagram-clone-d78a1.appspot.com',
    iosBundleId: 'com.prjs.flutter.instagramExample',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuTP39IopXFiEJtAVfXHMAPNG3jujWrWw',
    appId: '1:358203995156:web:db867c8183cc3aa416e301',
    messagingSenderId: '358203995156',
    projectId: 'instagram-clone-d78a1',
    authDomain: 'instagram-clone-d78a1.firebaseapp.com',
    databaseURL: 'https://instagram-clone-d78a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'instagram-clone-d78a1.appspot.com',
    measurementId: 'G-81FTHLHKK8',
  );

}